"""Onboarding wizard for mem-mesh.

Performs 3-step setup:
1. API server setup (check connectivity, or install via Docker/source)
2. Hook installation
3. MCP configuration check
"""

import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

from app.cli.hooks.colors import bold, dim, err, header, info, ok, warn
from app.cli.hooks.constants import CLAUDE_HOOKS_DIR, DEFAULT_URL
from app.cli.hooks.status import check_connectivity, resolve_api_url


def _detect_target() -> str:
    """Auto-detect which IDE to install hooks for."""
    targets = []
    if CLAUDE_HOOKS_DIR.parent.exists():
        targets.append("claude")
    kiro_dir = Path.home() / ".kiro"
    if kiro_dir.exists():
        targets.append("kiro")
    cursor_dir = Path.home() / ".cursor"
    if cursor_dir.exists():
        targets.append("cursor")

    if not targets:
        return "claude"
    if len(targets) == 1:
        return targets[0]
    return "all"



def _has_docker() -> bool:
    """Check if docker and docker-compose are available."""
    return shutil.which("docker") is not None


def _find_compose_file() -> Optional[Path]:
    """Find docker-compose.yml in current working directory."""
    candidates = [
        Path.cwd() / "docker-compose.yml",
        Path.cwd() / "docker-compose.mem-mesh.yml",
    ]
    for p in candidates:
        if p.exists():
            return p
    return None


def _prompt_choice(prompt: str, options: list[str], default: str = "") -> str:
    """Simple numbered choice prompt."""
    for i, opt in enumerate(options, 1):
        print(f"    {bold(str(i))}. {opt}")
    while True:
        raw = input(f"  {prompt} ").strip()
        if not raw and default:
            return default
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1]
        print(f"    Enter 1-{len(options)}")


# Embedding model choices for onboarding
EMBEDDING_MODELS = [
    (
        "intfloat/multilingual-e5-large",
        1024,
        "Best quality, multilingual, ~1.1GB",
    ),
    (
        "intfloat/multilingual-e5-base",
        768,
        "Good balance, multilingual, ~470MB",
    ),
    (
        "intfloat/multilingual-e5-small",
        384,
        "Fastest, multilingual, ~118MB",
    ),
    (
        "all-MiniLM-L6-v2",
        384,
        "English-optimized, lightweight, ~80MB",
    ),
]


def _prompt_value(prompt: str, default: str) -> str:
    """Prompt for a value with a default."""
    raw = input(f"  {prompt} [{bold(default)}]: ").strip()
    return raw if raw else default


def _prompt_docker_options() -> dict:
    """Interactive Docker configuration prompts."""
    print()
    print(f"  {header('Docker Configuration')}")
    print()

    # --- Port ---
    port = _prompt_value("Port", "8000")
    try:
        port = int(port)
    except ValueError:
        port = 8000
    print()

    # --- Embedding model ---
    print(f"  {bold('Embedding Model')}")
    print(f"  {dim('Determines search quality and resource usage.')}")
    print()
    model_options = []
    for name, dim_size, desc in EMBEDDING_MODELS:
        model_options.append(f"{name} {dim(f'({desc}, dim={dim_size})')}")
    chosen_model_opt = _prompt_choice("Choose [1]: ", model_options, default=model_options[0])
    model_idx = model_options.index(chosen_model_opt)
    model_name, embedding_dim, _ = EMBEDDING_MODELS[model_idx]
    print()

    # --- Volume type ---
    print(f"  {bold('Data Storage')}")
    print(f"  {dim('Where to store the SQLite database and model cache.')}")
    print()
    volume_options = [
        f"Docker volume {dim('(managed by Docker, portable)')}",
        f"Local directory {dim(f'(./mem-mesh-data in current dir)')}"
    ]
    chosen_volume = _prompt_choice("Choose [1]: ", volume_options, default=volume_options[0])
    use_local_volume = volume_options.index(chosen_volume) == 1
    print()

    return {
        "port": port,
        "model_name": model_name,
        "embedding_dim": embedding_dim,
        "use_local_volume": use_local_volume,
    }


def _generate_compose_file(
    port: int = 8000,
    model_name: str = "intfloat/multilingual-e5-large",
    embedding_dim: int = 1024,
    use_local_volume: bool = False,
) -> Path:
    """Generate a docker-compose.yml in the current directory."""
    if use_local_volume:
        volume_line = "      - ./mem-mesh-data:/app/data"
        volumes_section = ""
    else:
        volume_line = "      - mem-mesh-data:/app/data"
        volumes_section = "\nvolumes:\n  mem-mesh-data:\n"

    content = f"""\
# Generated by: mem-mesh install
# mem-mesh API server (Docker)
services:
  mem-mesh:
    image: mem-mesh:latest
    container_name: mem-mesh
    ports:
      - "{port}:8000"
    volumes:
{volume_line}
    environment:
      - DATABASE_PATH=/app/data/memories.db
      - EMBEDDING_MODEL={model_name}
      - EMBEDDING_DIM={embedding_dim}
      - LOG_LEVEL=INFO
      - MEM_MESH_SERVER_HOST=0.0.0.0
      - MEM_MESH_SERVER_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
{volumes_section}"""

    compose_path = Path.cwd() / "docker-compose.mem-mesh.yml"
    compose_path.write_text(content, encoding="utf-8")
    return compose_path


def _setup_server_docker(url: str) -> tuple[bool, str]:
    """Set up server via Docker."""
    import time

    compose_file = _find_compose_file()

    if not compose_file:
        docker_opts = _prompt_docker_options()

        print(f"  {dim('Generating docker-compose.mem-mesh.yml...')}")
        compose_file = _generate_compose_file(**docker_opts)
        print(f"  Created: {ok(str(compose_file))}")

        # Update URL if port changed
        port = docker_opts["port"]
        if port != 8000:
            url = f"http://localhost:{port}"

    print(f"  Compose file: {info(str(compose_file))}")
    print(f"  {dim('Running: docker compose up -d')}")

    result = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "up", "-d"],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"  {err('Docker startup failed')}")
        for line in result.stderr.strip().splitlines()[-3:]:
            print(f"    {dim(line)}")
        return False, url

    print(f"  {ok('Docker containers started')}")

    print(f"  {dim('Waiting for server to be ready...')}")
    for _attempt in range(5):
        time.sleep(2)
        reachable, msg = check_connectivity(url)
        if reachable:
            print(f"  {ok(f'Server ready ({msg})')}")
            return True, url
    print(f"  {warn('Server started but not yet reachable. It may need more time.')}")
    return False, url


def _setup_server_source() -> tuple[bool, str]:
    """Set up server via pip install mem-mesh[server]."""
    print(f"  {dim('Running: pip install mem-mesh[server]')}")

    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "mem-mesh[server]"],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"  {err('Installation failed')}")
        for line in result.stderr.strip().splitlines()[-3:]:
            print(f"    {dim(line)}")
        return False, DEFAULT_URL

    print(f"  {ok('Server package installed')}")
    print()
    print(f"  {bold('To start the server:')}")
    print(f"    {info('mem-mesh serve')}")
    print(f"    {dim('or: mem-mesh serve --reload  (development mode)')}")
    return False, DEFAULT_URL  # Not running yet, user must start manually


def _fail(message: str, force: bool) -> None:
    """Print error and exit unless --force is set."""
    print(f"  {err(message)}")
    if force:
        print(f"  {dim('--force: continuing despite error')}")
    else:
        print(f"  {dim('Use --force to continue despite errors.')}")
        sys.exit(1)


def cmd_onboarding(
    url: Optional[str] = None,
    target: str = "auto",
    profile: str = "standard",
    yes: bool = False,
    force: bool = False,
) -> None:
    """Run the onboarding wizard."""
    print()
    print(header("=== mem-mesh setup ==="))
    print()

    # --- Step 1: Server setup ---
    print(bold("[1/3] API Server"))

    if url:
        resolved_url = url.rstrip("/")
        source = "command line"
    else:
        resolved_url, source = resolve_api_url()

    print(f"  URL: {info(resolved_url)} {dim(f'(from {source})')}")

    reachable, message = check_connectivity(resolved_url)
    if reachable:
        print(f"  Status: {ok(message)}")
    else:
        print(f"  Status: {err(message)}")
        print()

        if yes:
            print(dim("  (--yes: skipping server setup)"))
        else:
            # Ask how to set up the server
            print(f"  {warn('Server is not running. How would you like to set it up?')}")
            print()

            has_docker = _has_docker()
            compose_exists = _find_compose_file() is not None

            options = []
            option_keys = []

            if has_docker and compose_exists:
                options.append(f"Docker {dim('(docker compose up -d)')}")
                option_keys.append("docker")
            elif has_docker:
                options.append(f"Docker {dim('(docker-compose.yml not found in cwd)')}")
                option_keys.append("docker")

            options.append(f"Source install {dim('(pip install mem-mesh[server])')}")
            option_keys.append("source")

            options.append(f"Skip {dim('(set up server later)')}")
            option_keys.append("skip")

            chosen = _prompt_choice(
                f"Choose [{1}]: ",
                options,
                default=options[0],
            )
            chosen_key = option_keys[options.index(chosen)]

            print()
            if chosen_key == "docker":
                reachable, resolved_url = _setup_server_docker(resolved_url)
                if not reachable:
                    _fail("Server setup failed.", force)
            elif chosen_key == "source":
                reachable, resolved_url = _setup_server_source()
                # Source install doesn't start server, not a failure
            # else: skip
    print()

    # --- Step 2: Hook installation ---
    print(bold("[2/3] Hook Installation"))

    if target == "auto":
        target = _detect_target()
        print(f"  Detected IDE: {info(target)}")
    else:
        print(f"  Target:       {info(target)}")
    print(f"  Profile:      {info(profile)}")

    if not yes:
        answer = input(f"  Install hooks for {target}? [Y/n] ").strip().lower()
        if answer in ("n", "no"):
            print(dim("  Skipping hook installation."))
            print()
            from app.cli.mcp_config import run_mcp_setup

            run_mcp_setup(url=resolved_url, yes=yes)
            _print_summary(resolved_url, reachable, False, target)
            return

    install_url = resolved_url if resolved_url else DEFAULT_URL

    try:
        from app.cli.install_hooks import cmd_install

        cmd_install(target, install_url, "api", "", profile)
        hooks_installed = True
        print(f"  {ok('Hooks installed successfully.')}")
    except Exception as e:
        hooks_installed = False
        _fail(f"Hook installation failed: {e}", force)
    print()

    # --- Step 3: MCP config ---
    from app.cli.mcp_config import run_mcp_setup

    run_mcp_setup(url=resolved_url, yes=yes)

    # --- Summary ---
    _print_summary(resolved_url, reachable, hooks_installed, target)



def _print_summary(url: str, server_ok: bool, hooks_ok: bool, target: str) -> None:
    """Print onboarding summary."""
    print(header("=== Setup Complete ==="))
    print()
    print(f"  API server:  {ok(url) if server_ok else warn(url + ' (not running)')}")
    print(
        f"  Dashboard:   {info(url + '/dashboard') if server_ok else dim('unavailable')}"
    )
    print(
        f"  Hooks:       {ok(f'installed ({target})') if hooks_ok else warn('not installed')}"
    )
    print()
    if not server_ok:
        print(f"  {bold('Next step:')} Start the server with {info('mem-mesh serve')}")
        print(dim("             Or: docker compose up -d"))
    print(dim("  Run 'mem-mesh status' for full system check."))
    print(dim("  Run 'mem-mesh hooks doctor' for hook diagnostics."))
    print()
